name: Run Tests

on:
  push:
    branches:
      - "*"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup Ruby head
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: jruby

      - name: Setup Node Latest
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Get yarn cache
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >>$GITHUB_OUTPUT

      - name: Cache yarn
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Cache gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          yarn install --frozen-lockfile
      
      - name: Run tests
        run: bundle exec rake
